artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: http://freakonometrics.free.fr/german_credit.csv
  local_data_file: artifacts/data_ingestion/data.csv
  unzip_dir: artificats/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_file_path: artifacts/data_ingestion/data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_file_path: artifacts/data_transformation/train.csv
  test_file_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
